### ISSUE TITLE
tab out disables emmet

### ISSUE THREAD

**Issue by germainep** [dag0310/tab-out#1]
Using this plugin disables the emmet expand on tab feature.

**Comment by dag0310** [comment]
Unfortunately Brackets does not support having the same key binding (in this case Tab) in different plugins (only one will work). So, since my plugin does not make sense with any other key binding the only thing I can do is add a menu entry to dis-/enable the plugin :-/ But other suggestions are very welcome!

**Comment by germainep** [comment]
thanks for the reply I'll just set a new key binding to emmet

**Comment by dag0310** [comment]
Great, so at least there is a work-around :+1: I added a warning to the README.md.

**Comment by KevinBatdorf** [comment]
`option+tab` seems reasonable and wouldn't be difficult to get used to.

**Comment by dag0310** [comment]
My plugin is not called "Option+Tab Out" :stuck_out_tongue: 
Seriously though, this would be a Mac only feature and I'd like to keep it simple/universal.

Disclaimer: I'm a Windows, OSX and Linux user.

**Comment by KevinBatdorf** [comment]
I think the keybinding is the same for the alt and option keys. It's platform agnostic. 

But you could just keep it as is, then add a setting to change the key binding. just my two cents :)

**Comment by dag0310** [comment]
Nope, Windows and most Linux' use Alt+Tab already for switching between open applications.

But: I was just going to add a toggle option "Tab Out: Use Alt+Tab instead of Tab (Mac only)". Guess I can live with that :wink:

**Comment by dag0310** [comment]
Toggle option for Mac implemented and ready to update (v1.0.2)! :smiley:

**Comment by KevinBatdorf** [comment]
Works like a charm! But I think you could find a key binding for both, and still keep the name of the plugin.

What are you using in place of emmet?

**Comment by dag0310** [comment]
On Windows there is no key binding that would work. There is only Shift, Ctrl, Win and Alt and all combinations of those with Tab are already used either by Brackets or Windows itself. I do not use Emmet actually, but I would use something like Alt+Shift+E.
