### ISSUE TITLE
JSON validation error while enabling ALT + TAB on mac

### ISSUE THREAD

**Issue by brandflownet** [dag0310/tab-out#3]
After choosing TabOut from Navigate menu, I am getting error that keymap.json cannot be validated. 

```
{
    "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
    "overrides": {
        ["keys": "enter"], "command": "move", "args": {"by": "characters", "forward": true}, "context":
        { "key": "following_text", "operator": "regex_contains", "operand": "^)\"\\]]", "match_all": true },
        { "key": "auto_complete_visible", "operator": "equal", "operand": false }

    }

}
```

Above auto generated code which causes issues.

**Comment by dag0310** [comment]
I am using Brackets 1.6 on OSX El Capitan and cannot reproduce this problem, i.e. it "Works on My Machine" TM. Maybe you have some other plugin installed which interferes with mine? I guess you need Alt+Tab because Tab is already taken by some other plugin like "Emmet", right?

**Comment by brandflownet** [comment]
I've just upgraded to the newest version (1.7) and the issue is still there... I am using Emmet, that's why I wanted to remap it to Alt Tab. 

Could you please share with me your config file? I am still getting JSON validation error: 

> {
>     "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
>     "overrides": {
>         ["keys": "enter"], "command": "move", "args": {"by": "characters", "forward": true}, "context":
>         { "key": "following_text", "operator": "regex_contains", "operand": "^)\"\]]", "match_all": true },
>         { "key": "auto_complete_visible", "operator": "equal", "operand": false }
> 
> ```
> }
> ```
> 
> }

**Comment by dag0310** [comment]
This is my keymap.json file:

```
{
    "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
    "overrides": {

    }
}
```

I don't use Emmet, so there could be a conflict with it. Maybe try to use no keymap overrides like I do and deactivate Emmet temporarily. Maybe then we know what causes this problem at least.
